on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features && ls -l */*
      - uses: actions/upload-artifact@v3
        with:
          path: /home/runner/work/hello-world-rust/hello-world-rust/target/release/
          name: hello-world
          retention-days: 5
